### ISSUE TITLE
알려진 문제

### ISSUE THREAD

**Issue by JeonDohyeon** [JeonDohyeon/imitated-seed#1]
`@test-server` https://wiki.jdh5968.pe.kr
`@test-server-branch` `flight`
`@forked-from` `gdl-blue/imitated-seed-2`
* 로그인 후 최대 10분간 로그인된 상태로 안 뜸
  - 임시 해결 방법: 다른 메뉴로 들어가면 로그인된 상태로 표시됩니다.
* 한 번 방문한 페이지의 캐시 지속 시간이 너무 김 (약 2분 ~ 최대 10분)
* `{{{` `}}}` 매크로 (중괄호 문법) 파싱 문제 gdl-blue#14
  - 상세: 문서 하나에 최대 2개까지만 파싱되며, 3개 이상은 RAW Content 하나와 Rich Content 하나로 렌더링됨
  - 추가: 표 안에만 있으면 크게 꼬이지 않는 느낌이다.
  - 추가: `}}}`는 아얘 파싱이 안 된다. 얘를 파싱하면 대부분은 고쳐질 느낌이긴 한데...
    + 고급 문법 안 되는 건 둘째치고, 얘가 파싱이 돼야 사진 넣기가 가능하다. 지금은 아마 3개 넣으면 문서가 박살난다.
* 주석의 최대 파싱 개수가 하나임 gdl-blue#31
* 숨긴 목차 문법이 렌더링되지 않음
* 편집 주석 문법(`##`)이 적용된 줄이 빈 줄로 렌더링됨
  - 원래: 렌더링되면 안 됨
* 다크모드 렌더링 불가 문제
  - 스킨 문제다. 다크모드 보려면 일단 buma로.
  - 렌더러에서 다크모드 지원이 안 되긴 한다. 다크모드 쓰면 눈뽕 좀 오질 거다. 가독성만 나쁘고.
* 파일 업로드 불가 문제 gdl-blue#15
  - 파일 서버 개발중이랜다.
* ACL 관리 권한 목록에 일부 필수 권한이 노출되지 않음 gdl-blue#27
  - 일단 perm:aclgroup 추가해서 PR 올렸고 나머지도 차차 추가할 예정
  - `@fork` aploga#3
* 토론 `#n`을 연달아 사용할 수 없음 gdl-blue#23
* 토론 업뎃이 느림 ![Screenshot_20221108-164437_Kiwi Browser](https://user-images.githubusercontent.com/117263963/200504129-f6c921b6-c148-408b-af58-e4ad30aee192.jpg) 
* 나머지는 리폿 시 추가하겠습니다.

**Comment by aploga** [comment]
perm:aclgroup은 __ACL 관리자__가 아닌__ ACL Group 관리자__ 입니다

**Comment by aploga** [comment]
~~여기서도 파싱이 안돼~~

**Comment by JeonDohyeon** [comment]
30ab3fcfb18822915d56c0684399afc9eb940beb - FIX: perm:aclgroup에 대한 표시 표현 수정

> perm:aclgroup은 **ACL 관리자**가 아닌** ACL Group 관리자** 입니다

반영했습니다

**Comment by JeonDohyeon** [comment]
Dupe: "토론 업뎃이 안 됨"은 "로그인 후 최대 10분간 로그인된 상태로 안 뜸" 및 "한 번 방문한 페이지의 캐시 지속 시간이 너무 김"과 중복됩니다.
해당 오류는 Shift + F5(캐시 지우고 전체 다시 다운로드)로도 갱신되지 않는 것으로 보아 코드 결함으로 추정됩니다. @aploga

**Comment by aploga** [comment]
캐시 문제인 듯 하군요. 감사합니다.
