### ISSUE TITLE
알려진 코드 이슈

### ISSUE THREAD

**Issue by JeonDohyeon** [JeonDohyeon/imitated-seed#2]
`@related` aploga#1

* main.js가 너무 김
  - 메인 코드 (이하 `lifecycle`) 길이가 main.js의 80% 이상인 게 화근인 것 같다
  - 램 16기가 스왑 8기가짜리 안드 탭에서 코드 여는데 3분 탭 닫는데 5분 걸린다
  - 램 8기가 윈도우 PC에서 크롬으로 코드 여는데 1분 탭 닫는데 4분 걸린다
* 코드의 Lifecycle이 매우 느림
  - redraw가 매 15초마다 일어나기만 해도 충분히 가능하지만, 문제는 지금 코드 자체가 멀티스레딩 지원이 없음
  - 최대 10분까지 redraw가 지연됨을 확인했으며, redraw 발생 시 사이트가 무한로딩 표시됨.
    + 무한로딩이 표시되더라도, Static 사이트라 실제 로딩은 발생하지 않는 것으로 파악됨.

**Comment by aploga** [comment]
지금 파서부터 분리해서 module & export로 부르는게 좋을 듯 합니다.

**Comment by aploga** [comment]
지금 겹치는 함수가 많아서 나중에 function.js로 따로 뺄겁니다.
