### ISSUE TITLE
권한 요청 처리 부탁드립니다.

### ISSUE THREAD

**Issue by poiega** [JeonDohyeon/imitated-seed#7]
### 무순 문제가 생겼나요?

https://wiki.jdh5968.pe.kr/thread/SadGiddyWashableNumber

### 브랜치 선택

flight (테스트위키 등)

**Comment by JeonDohyeon** [comment]
처리되었습니다. 확인 부탁드립니다.

> 처리 사항
grant를 포함한 모든 권한 부여
